{% set name = "napari-hough-circle-detector" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-hough-circle-detector-{{ version }}.tar.gz
  sha256: 7305814107bd8b199eb25d9bc6cbea469bdd6f727e6208be7e7e502727942e6e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - napari
    - numpy
    - python >={{ python_min }}
    - opencv
    - qtpy
    - scikit-image

test:
  imports:
    - napari_hough_circle_detector
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-hough-circle-detector/
  summary: An interactive Hough transform for napari.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
